/**
 * This file was generated by the JPA Modeler
 */
package tech.eats.art.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;

/**
 * @author John
 */
@Entity
public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String firstName;

    @Basic
    private String lastName;

    @ElementCollection
    @CollectionTable(name = "EMP_CERT", joinColumns = {
        @JoinColumn(name = "EMP_ID")})
    private List<Certificate> certificates;

    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "city", column = @Column(name = "HOME_CITY"))
        ,@AttributeOverride(name = "country", column = @Column(name = "HOME_COUNTRY"))
        ,@AttributeOverride(name = "pinCode.code", column = @Column(name = "HOME_CODE"))
        ,@AttributeOverride(name = "pinCode.prefix", column = @Column(name = "HOME_PREFIX"))
        ,@AttributeOverride(name = "state", column = @Column(name = "HOME_STATE"))
        ,@AttributeOverride(name = "street", column = @Column(name = "HOME_STREET"))})
    private Address homeAddress;

    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "city", column = @Column(name = "OFC_CITY"))
        ,@AttributeOverride(name = "country", column = @Column(name = "OFC_COUNTRY"))
        ,@AttributeOverride(name = "pinCode.code", column = @Column(name = "OFC_CODE"))
        ,@AttributeOverride(name = "pinCode.prefix", column = @Column(name = "OFC_PREFIX"))
        ,@AttributeOverride(name = "state", column = @Column(name = "OFC_STATE"))
        ,@AttributeOverride(name = "street", column = @Column(name = "OFC_STREET"))})
    private Address officeAddress;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public List<Certificate> getCertificates() {
        return this.certificates;
    }

    public void setCertificates(List<Certificate> certificates) {
        this.certificates = certificates;
    }

    public Address getHomeAddress() {
        return this.homeAddress;
    }

    public void setHomeAddress(Address homeAddress) {
        this.homeAddress = homeAddress;
    }

    public Address getOfficeAddress() {
        return this.officeAddress;
    }

    public void setOfficeAddress(Address officeAddress) {
        this.officeAddress = officeAddress;
    }

}
