/**
 * This file was generated by the JPA Modeler
 */
package tech.eats.art.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

/**
 * @author John
 */
@Entity
@Table(name = "EMPLOYEE")
public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "FIRST_NAME")
    @Basic
    private String firstName;

    @Column(name = "LAST_NAME")
    @Basic
    private String lastName;

    @Column(name = "BIRTH_DATE")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date birthDate;

    @Column(name = "GENDER")
    @Basic
    @Enumerated
    private GenderType gender;

    @Basic
    private boolean active;

    @Column(name = "PROFILE_PIC")
    @Lob
    @Basic
    private byte[] profilePic;

    @OneToOne(optional = false, orphanRemoval = true, cascade = {CascadeType.MERGE, CascadeType.PERSIST}, targetEntity = Cubicle.class)
    @JoinColumn(name = "CUBICLE_ID")
    private Cubicle assignedCubicle;

    @ManyToMany(targetEntity = Project.class)
    @JoinTable(joinColumns = {
        @JoinColumn(name = "PROJECT_ID")}, inverseJoinColumns = {
        @JoinColumn(name = "EMPLOYEE_ID")})
    private Map<String, Project> projects;

    @Version
    private long version;

    @Transient
    private String age;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public GenderType getGender() {
        return this.gender;
    }

    public void setGender(GenderType gender) {
        this.gender = gender;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public byte[] getProfilePic() {
        return this.profilePic;
    }

    public void setProfilePic(byte[] profilePic) {
        this.profilePic = profilePic;
    }

    public Cubicle getAssignedCubicle() {
        return this.assignedCubicle;
    }

    public void setAssignedCubicle(Cubicle assignedCubicle) {
        this.assignedCubicle = assignedCubicle;
    }

    public Map<String, Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Map<String, Project> projects) {
        this.projects = projects;
    }

    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

}
