/**
 * This file was generated by the JPA Modeler
 */
package tech.eats.art.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author John
 */
@Embeddable
public class PinCode implements Serializable {

    @Basic
    private String prefix;

    @Basic
    private String code;

    public String getPrefix() {
        return this.prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
